# roles/webservers/tasks/main.yml

- name: Create instance(s)
  hosts: localhost
  connection: local
  gather_facts: no
  vars:
    gcp_project: studentjamk
    gcp_cred_kind: serviceaccount
    gcp_cred_file: ~/secret/ansible-service-account.json
    zone: "europe-north1-a"
    gce_image: projects/ubuntu-os-cloud/global/images/family/ubuntu-2004-lts
    gce_machine: e2-small
  tasks:
    - name: "{{ task_name }}"
      gcp_compute_instance:
        auth_kind: "{{ gcp_cred_kind }}"
        service_account_file: "{{ gcp_cred_file }}"
        name: "{{ machine_name }}"
        machine_type: "{{ gce_machine }}"
        zone: "{{ zone }}"
        project: "{{ gcp_project }}"
        disks:
          - auto_delete: true
            boot: true
            initialize_params:
              source_image: "{{ gce_image }}"
        network_interfaces:
          - access_configs:
            - name: External NAT
              type: ONE_TO_ONE_NAT
